title: Masa Blog - GTI
email: af24520985@gmail.com
description: >- 
  隨筆隨記的地方
baseurl: "/" 
url: "https://kstmasa.github.io/blog/" 
github_username:  kstmasa

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin

disqus :
  shortname : MasaBlogs    
google_analytics : UA-141730516-1
